.TH dablin 1 "January 18 2018"
.SH NAME
dablin \- DAB & DAB+ receiver client
.SH SYNOPSIS
.B dablin
.SH DESCRIPTION
This manual page documents briefly the
.B dablin
and
.B dablin_gtk
commands.
.PP
\fBdablin\fP plays a DAB and DAB+ audio service – either from a received live
transmission or from a stored ensemble recording (frame-aligned ETI-
NI). Both DAB (MP2) and DAB+ (AAC-LC, HE-AAC, HE-AAC v2) services are
supported by DABlin.
.TP
dablin_gtk is the GUI version for the same audio service.
.SH OPTIONS
.TP
.B \-h
Show summary of options
.TP
.B \-d <binary>
Use DAB live source (using the mentioned binary)
.TP
.B \-c <ch>
Channel to be played (requires DAB live source)
.TP
.B \-s <sid>
ID of the service to be played
.TP
.B \-x <scids>
ID of the service component to be played (requires service ID)
.TP
.B \-r <subchid>
ID of the sub-channel (DAB) to be played
.TP
.B \-R <subchid>
ID of the sub-channel (DAB+) to be played
.TP
.B \-g <gain>
USB stick gain to pass to DAB live source (auto gain is default)
.TP
.B \-p
Output PCM to stdout instead of using SDL
.TP
.B file
Input file to be played (stdin, if not specified)
